#!/bin/sh
#
# @name MotoVisio m5150
#
# @type Vectored 6 DOF UUV
# @class Underwater Robot
#
# @output MAIN1 motor 1 CCW, bow starboard horizontal, , propeller CCW
# @output MAIN2 motor 2 CCW, bow port horizontal, propeller CCW
# @output MAIN3 motor 3 CW, stern starboard horizontal, propeller CW
# @output MAIN4 motor 4 CW, stern port horizontal, propeller CW
# @output MAIN5 motor 5 CCW, bow starboard vertical, propeller CCW
# @output MAIN6 motor 6 CW, stern port vertical, propeller CW
#
# @maintainer Ryan Meagher <ryan@motovisio.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.uuv_defaults

#Set data link loss failsafe mode (0: disabled)
param set-default NAV_DLL_ACT 0

# disable circuit breaker for airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128

# companion computer is connected via USB permanently
param set-default CBRK_USB_CHK 197848

param set-default CBRK_IO_SAFETY 22027

# Allow running off 5V supply for testing
param set-default CBRK_SUPPLY_CHK 894281

# Use joystick
param set-default COM_RC_IN_MODE 1

# Disable warning for SD card not present
param set-default COM_ARM_SDCARD 0

param set-default COM_PREARM_MODE 0

param set-default MAV_1_CONFIG 102

param set-default BAT_N_CELLS 4

param set-default PWM_MAIN_MAX 1900
param set-default PWM_MAIN_MIN 1100
param set-default PWM_MAIN_DISARM 1500

set MAV_TYPE 12
set PWM_OUT 123456
# set MIXER IO_pass
set MIXER vectored3dof

